export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const USER_ROUTE = '/user'
export const REGISTRATION_ROUTE = '/registration'
export const GALLERY_ROUTE = '/'
export const IMAGE_ROUTE = '/image'
